"""
Django settings for conexiones project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

INTERNAL_IPS = ["127.0.0.1"]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
}

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "simple_history",
    "clientes.apps.ClientesConfig",
    "planes.apps.PlanesConfig",
    "instalaciones.apps.InstalacionesConfig",
    "facturacion.apps.FacturacionConfig",
    "base.apps.BaseConfig",
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "conexiones.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates',],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "conexiones.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-CO"

TIME_ZONE = "America/Bogota"

USE_I18N = True
USE_THOUSAND_SEPARATOR = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = '/app/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

UNFOLD = {
    "SITE_TITLE": "Arint Conexiones",
    "SITE_HEADER": "Arint Conexiones",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("images/logo-light.svg"),
        "dark": lambda request: static("images/logo-dark.svg"),
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "href": lambda request: static("images/logo-light.svg"),
        },
    ],
    "COLORS": {
        "primary": {
            "50": "236 253 245",
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "5 150 105",
            "600": "4 120 87",
            "700": "6 95 70",
            "800": "6 78 59",
            "900": "2 44 34",
            "950": "1 20 15",
        },
    },
    "DASHBOARD_CALLBACK": "base.views.dashboard_callback",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Navegación"),
                "separator": False,
                "items": [
                    {
                        "title": _("Panel de control"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Gestión"),
                "separator": True,
                "items": [
                    {
                        "title": _("Caja rápida"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("portal_caja"),
                        "permission": lambda request: request.user.is_staff,
                        "badge": "conexiones.utils.get_nuevo_badge",
                    },
                    {
                        "title": _("Cargos"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:facturacion_cargo_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_cargo"),
                        "badge": "conexiones.utils.get_nuevo_badge",
                    },
                    {
                        "title": _("Transacciones"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:facturacion_transaccion_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_transaccion"),
                        "badge": "conexiones.utils.get_nuevo_badge",
                    },

                    {
                        "title": _("Facturas"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:facturacion_factura_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_factura"),
                    },
                    {
                        "title": _("Clientes"),
                        "icon": "people",
                        "link": reverse_lazy("admin:clientes_cliente_changelist"),
                        "permission": lambda request: request.user.has_perm("clientes.view_cliente"),
                    },
                    {
                        "title": _("Instalaciones"),
                        "icon": "router",
                        "link": reverse_lazy("admin:instalaciones_instalacion_changelist"),
                        "permission": lambda request: request.user.has_perm("instalaciones.view_intalacion"),
                    },
                    {
                        "title": _("Planes"),
                        "icon": "layers",
                        "link": reverse_lazy("admin:planes_plan_changelist"),
                        "permission": lambda request: request.user.has_perm("planes.view_plan"),
                    },
                ],
            },
            {
                "title": _("Administración"),
                "separator": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
        ],
    },
}

CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_TIMEZONE = TIME_ZONE

WA_PHONE_ID = os.getenv('WA_PHONE_ID', '')
WA_TOKEN = os.getenv('WA_TOKEN', '')

PAYMENT_NEQUI = os.getenv('PAYMENT_NEQUI', '[]')
PAYMENT_BREVE = os.getenv('PAYMENT_BREVE', '[]')
PAYMENT_BANCOLOMBIA = os.getenv('PAYMENT_BANCOLOMBIA', '[]')
PAYMENT_EFECTIVO = os.getenv('PAYMENT_EFECTIVO', '[]')

LOCALE_PATHS = [BASE_DIR / 'locale']
