"""
Django settings for conexiones project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

INTERNAL_IPS = ["127.0.0.1"]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
}

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    # 'debug_toolbar.panels.profiling.ProfilingPanel',
]

# Application definition

SHARED_APPS = [
    "django_tenants",
    "nucleo_admin.apps.NucleoAdminConfig",
    "usuarios",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.staticfiles",
]

TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "usuarios",
    "simple_history",
    "clientes.apps.ClientesConfig",
    "planes.apps.PlanesConfig",
    "instalaciones.apps.InstalacionesConfig",
    "facturacion.apps.FacturacionConfig",
    "base.apps.BaseConfig",
    "redes.apps.RedesConfig",
    "debug_toolbar",
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "nucleo_admin.EmpresaISP"
TENANT_DOMAIN_MODEL = "nucleo_admin.Dominio"

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "nucleo_admin.middleware.TenantSuspensionMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

AUTH_USER_MODEL = "usuarios.User"

ROOT_URLCONF = "conexiones.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates',],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "conexiones.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-CO"

TIME_ZONE = "America/Bogota"

USE_I18N = True
USE_THOUSAND_SEPARATOR = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = '/app/staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

def obtener_logo_inquilino(request):
    if hasattr(request, 'tenant') and request.tenant.schema_name != 'public' and request.tenant.logo:
        return request.tenant.logo.url
    return static("images/logo-nucleo.svg")

def obtener_nombre_inquilino(request):
    if hasattr(request, 'tenant') and request.tenant.schema_name != 'public':
        return request.tenant.name
    return "NucleoISP"

UNFOLD = {
    "SITE_TITLE": obtener_nombre_inquilino,
    "SITE_HEADER": obtener_nombre_inquilino,
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": obtener_logo_inquilino,
        "dark": obtener_logo_inquilino,
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "href": obtener_logo_inquilino,
        },
    ],
    "COLORS": {
        "primary": {
            "50": "236 253 245",
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "5 150 105",
            "600": "4 120 87",
            "700": "6 95 70",
            "800": "6 78 59",
            "900": "2 44 34",
            "950": "1 20 15",
        },
    },
    "DASHBOARD_CALLBACK": "base.views.dashboard_callback",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Navegación",
                "separator": False,
                "items": [
                    {
                        "title": "Panel de control",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": "Administración",
                "separator": True,
                "items": [
                    {
                        "title": "Empresas",
                        "icon": "business",
                        "link": reverse_lazy("admin:nucleo_admin_empresaisp_changelist"),
                        "permission": lambda request: request.user.is_superuser and hasattr(request, "tenant") and request.tenant.schema_name == "public",
                    },
                    {
                        "title": "Dominios",
                        "icon": "language",
                        "link": reverse_lazy("admin:nucleo_admin_dominio_changelist"),
                        "permission": lambda request: request.user.is_superuser and hasattr(request, "tenant") and request.tenant.schema_name == "public",
                    },
                    {
                        "title": "Paquete",
                        "icon": "package",
                        "link": reverse_lazy("admin:nucleo_admin_paquete_changelist"),
                        "permission": lambda request: request.user.is_superuser and hasattr(request, "tenant") and request.tenant.schema_name == "public",
                    },
                ],
            },
            {
                "title": "Gestión de clientes",
                "separator": True,
                "items": [
                    {
                        "title": "Clientes",
                        "icon": "people",
                        "link": reverse_lazy("admin:clientes_cliente_changelist"),
                        "permission": lambda request: request.user.has_perm("clientes.view_cliente") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Instalaciones",
                        "icon": "router",
                        "link": reverse_lazy("admin:instalaciones_instalacion_changelist"),
                        "permission": lambda request: request.user.has_perm("instalaciones.view_intalacion") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Planes",
                        "icon": "layers",
                        "link": reverse_lazy("admin:planes_plan_changelist"),
                        "permission": lambda request: request.user.has_perm("planes.view_plan") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                ],
            },
            {
                "title": "Facturación y cobros",
                "separator": True,
                "items": [
                    {
                        "title": "Caja rápida",
                        "icon": "point_of_sale",
                        "link": reverse_lazy("portal_caja"),
                        "permission": lambda request: request.user.is_staff and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Facturas",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:facturacion_factura_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_factura") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Cargos",
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:facturacion_cargo_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_cargo") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Transacciones",
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:facturacion_transaccion_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_transaccion") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                ],
            },
            {
                "title": "Redes e Infraestructura",
                "separator": True,
                "items": [
                    {
                        "title": "Routers",
                        "icon": "dns",
                        "link": reverse_lazy("admin:redes_router_changelist"),
                        "permission": lambda request: request.user.has_perm("redes.view_router") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                ],
            },
            {
                "title": "Ajustes generales",
                "separator": True,
                "items": [
                    {
                        "title": "Métodos de pago",
                        "icon": "payments",
                        "link": reverse_lazy("admin:facturacion_metodopago_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_metodopago") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                    {
                        "title": "Regla de reconexión",
                        "icon": "settings",
                        "link": reverse_lazy("admin:facturacion_configuracionfacturacion_changelist"),
                        "permission": lambda request: request.user.has_perm("facturacion.view_configuracionfacturacion") and hasattr(request, "tenant") and request.tenant.schema_name != "public",
                    },
                ],
            },
            {
                "title": "Administración",
                "separator": True,
                "items": [
                    {
                        "title": "Usuarios",
                        "icon": "person",
                        "link": reverse_lazy("admin:usuarios_user_changelist"),
                        "permission": lambda request: request.user.has_perm("usuarios.view_user"),
                    },
                    {
                        "title": "Grupos",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
        ],
    },
}

CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Soporte NucleoISP <no-reply@nucleoisp.com>")

LOCALE_PATHS = [BASE_DIR / 'locale']
