services:
  web:
    build: .
    container_name: conexiones_dev_web
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - /app/.venv
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      RUN_MIGRATIONS: "true"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: conexiones_dev_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:17.5
    container_name: conexiones_dev_db
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  celery_worker:
    build: .
    container_name: conexiones_dev_celery_worker
    command: uv run celery -A conexiones worker -l info
    volumes:
      - ./:/app
      - /app/.venv
      - /app/.uv-cache
    env_file:
      - .env.dev
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: conexiones_dev_celery_beat
    command: uv run celery -A conexiones beat -l info
    volumes:
      - ./:/app
      - /app/.venv
      - /app/.uv-cache
    env_file:
      - .env.dev
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
      - redis

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: conexiones_dev_wg_easy
    env_file:
      - .env.dev
    environment:
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - wg_easy_data_dev:/etc/wireguard
      - /lib/modules:/lib/modules:ro

volumes:
  postgres_data_dev:
  wg_easy_data_dev:
