# Generated by Django 5.2 on 2025-04-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad_megas', models.IntegerField(help_text='Velocidad del plan en Mbps')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'agregar planes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPlan',
            fields=[
                ('usuario_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inico', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('estado_servicio', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_plan', to='planes.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_plan', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'agregar plan',
                'verbose_name_plural': 'agregar planes',
            },
        ),
    ]
