# Generated by Django 5.2 on 2025-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad_megas', models.IntegerField(help_text='Velocidad del plan en Mbps')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'Agrega o modifica planes',
            },
        ),
    ]
