# Generated by Django 5.2 on 2025-12-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'planes'},
        ),
    ]
