# Generated by Django 5.2 on 2025-04-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioplan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'agregar planes a usuarios'},
        ),
    ]
