# Generated by Django 5.2 on 2026-06-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_plan_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_id',
            new_name='id',
        ),
    ]
