# Generated by Django 5.2 on 2026-06-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_rename_plan_id_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
