# Generated by Django 5.2 on 2025-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_alter_plan_options_alter_usuarioplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioplan',
            name='fecha_inico',
            field=models.DateTimeField(),
        ),
    ]
