# Generated by Django 5.2 on 2025-04-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_alter_usuarioplan_fecha_inico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'crear plan'},
        ),
        migrations.AlterModelOptions(
            name='usuarioplan',
            options={'verbose_name': 'plan a usuario', 'verbose_name_plural': 'agregar plan a usuario'},
        ),
    ]
