# Generated by Django 5.2 on 2025-04-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_alter_plan_options_alter_usuarioplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioplan',
            options={'verbose_name': 'plan a cliente', 'verbose_name_plural': 'agregar plan a cliente'},
        ),
    ]
