# Generated by Django 5.2 on 2025-06-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_alter_usuarioplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'Agrega o modifica planes'},
        ),
    ]
