# Generated by Django 5.2 on 2025-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0008_delete_usuarioplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='servicio_activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
