# Generated by Django 5.2 on 2025-07-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0009_plan_servicio_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='servicio_activo',
        ),
    ]
