# Generated by Django 5.2 on 2025-11-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intalacion',
            fields=[
                ('instalacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio_activo', models.BooleanField(default=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalacion', to='clientes.cliente')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan')),
            ],
            options={
                'verbose_name': 'instalacion a cliente',
                'verbose_name_plural': 'informacion de instalaciones',
            },
        ),
    ]
