# Generated by Django 5.2 on 2025-04-19 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intalacion',
            fields=[
                ('instalacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacion', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'instacion',
                'verbose_name_plural': 'instalaciones',
            },
        ),
    ]
