# Generated by Django 5.2 on 2026-06-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
        ('redes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio_activo', models.BooleanField(default=True)),
                ('ciclo_facturacion', models.IntegerField(choices=[(15, 'Quincenal'), (30, 'Mensual')], default=30)),
                ('pppoe_usuario', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pppoe_password', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='clientes.cliente')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redes.router')),
            ],
            options={
                'verbose_name': 'instalacion',
                'verbose_name_plural': 'instalaciones',
            },
        ),
    ]
