# Generated by Django 5.2 on 2025-12-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intalacion',
            options={'verbose_name': 'instalacion a cliente', 'verbose_name_plural': 'instalaciones'},
        ),
    ]
