# Generated by Django 5.2 on 2026-06-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='ip_estatica',
            field=models.GenericIPAddressField(blank=True, help_text='Opcional. Dejar en blanco para IP Dinámica.', null=True, verbose_name='IP Estática'),
        ),
    ]
