# Generated by Django 5.2 on 2025-04-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intalacion',
            options={'verbose_name': 'instacion', 'verbose_name_plural': 'Instalaciones'},
        ),
    ]
