# Generated by Django 5.2 on 2025-04-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0002_alter_intalacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intalacion',
            options={'verbose_name': 'instacion a usuario', 'verbose_name_plural': 'agregar instalacion a usuario'},
        ),
    ]
