# Generated by Django 5.2 on 2026-02-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('instalaciones', '0002_alter_intalacion_options'),
        ('planes', '0002_alter_plan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('instalacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio_activo', models.BooleanField(default=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='clientes.cliente')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan')),
            ],
            options={
                'verbose_name': 'instalacion a cliente',
                'verbose_name_plural': 'instalaciones',
            },
        ),
        migrations.DeleteModel(
            name='Intalacion',
        ),
    ]
