# Generated by Django 5.2 on 2026-07-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0002_instalacion_ip_estatica'),
        ('redes', '0004_alter_router_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redes.router'),
        ),
    ]
