# Generated by Django 5.2 on 2026-03-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('instalaciones', '0003_instalacion_delete_intalacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacion',
            options={'verbose_name': 'instalacion', 'verbose_name_plural': 'instalaciones'},
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
