# Generated by Django 5.2 on 2025-04-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0003_alter_intalacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intalacion',
            options={'verbose_name': 'instalacion a cliente', 'verbose_name_plural': 'agregar instalacion a cliente'},
        ),
    ]
