# Generated by Django 5.2 on 2026-03-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0004_alter_instalacion_options_alter_instalacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='ciclo_facturacion',
            field=models.IntegerField(choices=[(15, 'Quincenal'), (30, 'Mensual')], default=30),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='servicio_activo',
            field=models.BooleanField(default=True),
        ),
    ]
