# Generated by Django 5.2 on 2025-07-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0004_alter_intalacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intalacion',
            options={'verbose_name': 'instalacion a cliente', 'verbose_name_plural': 'informacion de instalaciones'},
        ),
    ]
