# Generated by Django 5.2 on 2025-07-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0005_alter_intalacion_options'),
        ('planes', '0008_delete_usuarioplan'),
        ('usuarios', '0009_alter_usuario_options_usuario_vereda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalacion',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan'),
        ),
        migrations.AlterField(
            model_name='intalacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalacion', to='usuarios.usuario'),
        ),
    ]
