# Generated by Django 5.2 on 2026-06-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0005_instalacion_ciclo_facturacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacion',
            old_name='instalacion_id',
            new_name='id',
        ),
    ]
