# Generated by Django 5.2 on 2025-07-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0006_intalacion_plan_alter_intalacion_usuario'),
        ('planes', '0008_delete_usuarioplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalacion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan'),
        ),
    ]
