# Generated by Django 5.2 on 2026-06-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0007_alter_instalacion_id'),
        ('redes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='pppoe_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='pppoe_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redes.router'),
        ),
    ]
