# Generated by Django 5.2 on 2025-07-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0007_alter_intalacion_plan'),
        ('planes', '0008_delete_usuarioplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalacion',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones', to='planes.plan'),
        ),
    ]
