# Generated by Django 5.2 on 2025-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0008_alter_intalacion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='intalacion',
            name='servicio_activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
