# Generated by Django 5.2 on 2025-07-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0009_intalacion_servicio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intalacion',
            name='servicio_activo',
            field=models.BooleanField(default=True),
        ),
    ]
