# Generated by Django 5.2 on 2026-06-24 22:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_gracia', models.PositiveIntegerField(default=3, help_text='Días adicionales después del corte del ciclo antes de cobrar reconexión', verbose_name='Días de gracia')),
            ],
            options={
                'verbose_name': 'Regla de Reconexión',
                'verbose_name_plural': 'Regla de Reconexión',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDetallePago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('saldo_previo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda inicial')),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda final')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical detalle pago',
                'verbose_name_plural': 'historical detalle pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('no aplica', 'No aplica')], default='no aplica', max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Transaccion',
                'verbose_name_plural': 'historical Transacciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('detalles', models.TextField(help_text='Ej: Número 3001234567 a nombre de Juan', verbose_name='Detalles de la cuenta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('no aplica', 'No aplica')], default='no aplica', max_length=15)),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cargo', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('instalacion', 'Instalacion'), ('reconexion', 'Reconexion')], default='mensualidad', max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], default='pendiente', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='clientes.cliente')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='instalaciones.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('saldo_previo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda inicial')),
                ('saldo_restante', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda final')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallepagos', to='facturacion.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(db_index=True, null=True)),
                ('periodo_final', models.DateField(null=True)),
                ('fecha_reconexion', models.DateField(null=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='factura_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura'),
        ),
        migrations.CreateModel(
            name='HistoricalCargo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_cargo', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('instalacion', 'Instalacion'), ('reconexion', 'Reconexion')], default='mensualidad', max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], default='pendiente', max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('factura_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'historical cargo',
                'verbose_name_plural': 'historical cargos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
