# Generated by Django 5.2 on 2025-05-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('detalle_factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_detalle', models.CharField(choices=[('mensualidad', 'Mensualidad'), ('instalación', 'Instalación'), ('reconexión', 'Reconexión')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=15)),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
            ],
        ),
    ]
