# Generated by Django 5.2 on 2025-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
