# Generated by Django 5.2 on 2025-12-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
    ]
