# Generated by Django 5.2 on 2025-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='periodo_inicio',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
