# Generated by Django 5.2 on 2025-07-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_pago_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_a_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
