# Generated by Django 5.2 on 2026-07-01 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='historicalcargo',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
