# Generated by Django 5.2 on 2025-07-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_factura_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
    ]
