# Generated by Django 5.2 on 2026-07-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('facturacion', '0003_alter_cargo_fecha_emision_and_more'),
        ('instalaciones', '0003_alter_instalacion_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='factura_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='instalaciones.instalacion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instalaciones.instalacion'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaciones', to='clientes.cliente'),
        ),
    ]
