# Generated by Django 5.2 on 2026-06-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_periodo_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='factura_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='pago_id',
            new_name='id',
        ),
    ]
