# Generated by Django 5.2 on 2025-07-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='facturacion.pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='periodo_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='periodo_inicio',
            field=models.DateField(null=True),
        ),
    ]
