# Generated by Django 5.2 on 2026-06-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_factura_id_alter_pago_id'),
        ('instalaciones', '0007_alter_instalacion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion'),
        ),
    ]
