# Generated by Django 5.2 on 2026-06-07 02:40

from django.db import migrations

def copiar_cliente_a_instalacion(apps, schema_editor):
    Factura = apps.get_model('facturacion', 'Factura')
    Instalacion = apps.get_model('instalaciones', 'Instalacion')

    for factura in Factura.objects.all():
        if factura.cliente_id:
            instalacion = Instalacion.objects.filter(cliente_id=factura.cliente_id).first()
            
            if instalacion:
                factura.instalacion_id = instalacion.id
                factura.save()

class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_factura_instalacion'),
    ]

    operations = [
        migrations.RunPython(copiar_cliente_a_instalacion),
    ]