# Generated by Django 5.2 on 2025-07-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_remove_factura_pago_pago_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='facturacion.pago'),
        ),
    ]
