# Generated by Django 5.2 on 2025-07-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_remove_pago_factura_factura_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.factura'),
        ),
    ]
