# Generated by Django 5.2 on 2026-06-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_auto_20260606_2140'),
        ('instalaciones', '0007_alter_instalacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='factura',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion'),
        ),
    ]
