# Generated by Django 5.2 on 2026-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_factura_cliente_alter_factura_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
