# Generated by Django 5.2 on 2025-07-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_factura_pago_pago_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'factura', 'verbose_name_plural': 'Administra facturas y pagos'},
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
    ]
