# Generated by Django 5.2 on 2025-07-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_factura_options_alter_pago_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('no aplica', 'No aplica')], default='no aplica', max_length=15),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('mensualidad', 'Mensualidad'), ('reconexion', 'Reconexion')], default='mensualidad', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
