# Generated by Django 5.2 on 2026-06-07 13:56

from django.db import migrations

def mover_datos_a_factura(apps, schema_editor):
    Factura = apps.get_model('facturacion', 'Factura')
    
    for factura in Factura.objects.all():
        pago = factura.pagos.first()
        
        if pago:
            factura.monto_total = pago.monto_pagado
            factura.estado = pago.estado
            factura.save()

class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_factura_estado_factura_monto_total'),
    ]

    operations = [
        migrations.RunPython(mover_datos_a_factura),
    ]
