# Generated by Django 5.2 on 2026-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_auto_20260607_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estado',
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
