# Generated by Django 5.2 on 2025-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_remove_pago_metodo_pago_metodo_pago_pago_tipo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_reconexion',
            field=models.DateField(null=True),
        ),
    ]
