# Generated by Django 5.2 on 2026-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_remove_pago_estado_alter_factura_monto_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-periodo_inicio'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], default='pendiente', max_length=10),
        ),
    ]
