# Generated by Django 5.2 on 2026-06-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_id'),
        ('facturacion', '0012_alter_factura_options_alter_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaciones', to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.transaccion'),
        ),
    ]
