# Generated by Django 5.2 on 2025-07-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_factura_codigo'),
        ('usuarios', '0011_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='codigo',
            new_name='codigo_factura',
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='usuarios.usuario'),
        ),
    ]
