# Generated by Django 5.2 on 2025-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_rename_codigo_factura_codigo_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('se acumula', 'Se acumula')], default='pendiente', max_length=10),
        ),
    ]
