# Generated by Django 5.2 on 2026-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_auto_20260609_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('no aplica', 'No aplica')], default='no aplica', max_length=15),
        ),
    ]
