# Generated by Django 5.2 on 2025-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
