# Generated by Django 5.2 on 2026-06-09 13:43

from django.db import migrations

def transferir_metodo_pago(apps, schema_editor):
    Pago = apps.get_model('facturacion', 'Pago')
    
    for pago in Pago.objects.all():
        if pago.transaccion:
            pago.transaccion.metodo_pago = pago.metodo_pago
            pago.transaccion.save()

class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_transaccion_metodo_pago'),
    ]

    operations = [
        migrations.RunPython(transferir_metodo_pago),
    ]
