# Generated by Django 5.2 on 2026-06-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_auto_20260609_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.transaccion'),
        ),
    ]
