# Generated by Django 5.2 on 2026-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_remove_pago_fecha_pago_remove_pago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial')], db_index=True, default='pendiente', max_length=10),
        ),
    ]
