# Generated by Django 5.2 on 2025-08-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_alter_pago_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='codigo_factura',
        ),
    ]
