# Generated by Django 5.2 on 2026-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
