# Generated by Django 5.2 on 2025-08-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_remove_factura_codigo_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'factura', 'verbose_name_plural': 'Agrega o modifica pagos'},
        ),
    ]
