# Generated by Django 5.2 on 2025-09-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_alter_factura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'Agrega o modifica pagos'},
        ),
    ]
