# Generated by Django 5.2 on 2026-06-20 12:49

from django.db import migrations
from django.utils import timezone

def migrar_datos_historicos(apps, schema_editor):
    Factura = apps.get_model('facturacion', 'Factura')
    Cargo = apps.get_model('facturacion', 'Cargo')
    Pago = apps.get_model('facturacion', 'Pago')
    DetallePago = apps.get_model('facturacion', 'DetallePago')
    Instalacion = apps.get_model('instalaciones', 'Instalacion')

    for instalacion in Instalacion.objects.filter(costo__gt=0):
        Cargo.objects.create(
            cliente=instalacion.cliente,
            instalacion=instalacion,
            tipo_cargo='instalacion',
            descripcion='Cargo por instalación (Histórico)',
            fecha_emision=instalacion.fecha_instalacion.date(),
            monto_total=instalacion.costo,
            saldo_pendiente=0,
            estado='pagado'
        )

    for factura in Factura.objects.select_related('instalacion__cliente').all():
        fecha = factura.periodo_inicio or timezone.now().date()

        cargo = Cargo.objects.create(
            cliente=factura.instalacion.cliente,
            instalacion=factura.instalacion,
            factura_origen=factura,
            tipo_cargo='mensualidad',
            descripcion='Cargo por mensualidad (Histórico)',
            fecha_emision=fecha,
            monto_total=factura.monto_total,
            saldo_pendiente=factura.monto_total,
            estado=factura.estado
        )

        pagos = Pago.objects.filter(factura=factura)
        for pago in pagos:
            if pago.transaccion:
                DetallePago.objects.create(
                    transaccion=pago.transaccion,
                    cargo=cargo,
                    monto_abonado=pago.monto_pagado
                )
                cargo.saldo_pendiente -= pago.monto_pagado

        cargo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_alter_transaccion_options_cargo_detallepago'),
    ]

    operations = [
        migrations.RunPython(migrar_datos_historicos),
    ]
