# Generated by Django 5.2 on 2025-09-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_alter_factura_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='monto_a_pagar',
        ),
    ]
