# Generated by Django 5.2 on 2026-06-20 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_migrar_historial_cargos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
