# Generated by Django 5.2 on 2026-06-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_alter_cargo_fecha_emision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
