# Generated by Django 5.2 on 2026-06-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_delete_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_total',
        ),
    ]
