# Generated by Django 5.2 on 2026-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_remove_factura_estado_remove_factura_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='saldo_previo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='saldo_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
