# Generated by Django 5.2 on 2026-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_detallepago_saldo_previo_detallepago_saldo_restante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepago',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='saldo_previo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda inicial'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='saldo_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deuda final'),
        ),
    ]
