# Generated by Django 5.2 on 2026-06-25 00:35

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaISP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL (Slug)')),
                ('admin_email', models.EmailField(blank=True, help_text='Se usará para crear el usuario administrador automáticamente', max_length=254, null=True, verbose_name='Email del Dueño')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_inquilinos/', verbose_name='Logo de la empresa')),
                ('wa_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Token de WhatsApp')),
                ('wa_phone_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Teléfono WhatsApp')),
            ],
            options={
                'verbose_name': 'Empresa ISP',
                'verbose_name_plural': 'Empresas ISP',
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='nucleo_admin.empresaisp')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
