# Generated by Django 5.2 on 2026-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo_admin', '0002_paquete_empresaisp_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaisp',
            name='routers_extras_contratados',
            field=models.IntegerField(default=0, help_text='Routers adicionales comprados por el ISP'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='limite_routers_incluidos',
            field=models.IntegerField(default=2, help_text='Routers base del paquete'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='precio_router_extra',
            field=models.DecimalField(decimal_places=2, default=25000.0, max_digits=10),
        ),
    ]
