# Generated by Django 5.2 on 2026-06-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo_admin', '0003_empresaisp_routers_extras_contratados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaisp',
            name='dias_gracia',
            field=models.IntegerField(default=3, help_text='Días adicionales antes de cortar el servicio por falta de pago'),
        ),
        migrations.AddField(
            model_name='empresaisp',
            name='estado_cuenta',
            field=models.CharField(choices=[('activa', 'Activa'), ('mora', 'En Mora'), ('suspendida', 'Suspendida')], default='activa', help_text='Estado financiero en la plataforma SaaS', max_length=20),
        ),
        migrations.AddField(
            model_name='empresaisp',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, help_text='Fecha en que debe pagar su mensualidad SaaS', null=True),
        ),
    ]
