# Generated by Django 5.2 on 2026-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo_admin', '0004_empresaisp_dias_gracia_empresaisp_estado_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaisp',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Dueño'),
        ),
        migrations.AlterField(
            model_name='empresaisp',
            name='dias_gracia',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='empresaisp',
            name='estado_cuenta',
            field=models.CharField(choices=[('activa', 'Activa'), ('mora', 'En Mora'), ('suspendida', 'Suspendida')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresaisp',
            name='fecha_proximo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresaisp',
            name='routers_extras_contratados',
            field=models.IntegerField(default=0),
        ),
    ]
