# Generated by Django 5.2 on 2025-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'direccion', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
