# Generated by Django 5.2 on 2025-04-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_direccion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'direccion a usuario', 'verbose_name_plural': 'agregar direccion a usuario'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'Crear usuario'},
        ),
    ]
