# Generated by Django 5.2 on 2025-04-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'direccion a cliente', 'verbose_name_plural': 'agregar direccion a cliente'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'Crear cliente'},
        ),
    ]
