# Generated by Django 5.2 on 2025-04-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'direccion a cliente', 'verbose_name_plural': 'crear/Editar direccion de cliente'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'Crear/Editar cliente'},
        ),
    ]
