# Generated by Django 5.2 on 2025-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_direccion_options_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='documento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
