# Generated by Django 5.2 on 2025-06-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_documento_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'Agrega o modifica clientes'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='vereda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
