# Generated by Django 5.2 on 2025-07-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_options_usuario_vereda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vereda',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
