# Generated by Django 5.2 on 2025-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('vereda', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Agrega o modifica clientes',
            },
        ),
    ]
