# Generated by Django 5.2 on 2026-06-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario_id',
            new_name='id',
        ),
    ]
