# Generated by Django 5.2 on 2026-06-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identificador', models.CharField(help_text='Ej: Nodo Principal, Torre Norte', max_length=100)),
                ('ip', models.GenericIPAddressField(help_text='Dirección IP del equipo Mikrotik', protocol='IPv4')),
                ('puerto_api', models.IntegerField(default=8728, help_text='Por defecto es 8728 (o 8729 si usa SSL)')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si el router está fuera de servicio')),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
            },
        ),
    ]
