# Generated by Django 5.2 on 2026-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='ip_vpn',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP asignada por la VPN (ej: 10.8.0.2)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='router',
            name='wg_client_id',
            field=models.CharField(blank=True, help_text='ID interno en el servidor WireGuard', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP pública (opcional si usa VPN)', null=True, protocol='IPv4'),
        ),
    ]
