# Generated by Django 5.2 on 2026-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0002_router_ip_vpn_router_wg_client_id_alter_router_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Opcional', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_vpn',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP asignada por la VPN', null=True, protocol='IPv4'),
        ),
    ]
