# Generated by Django 5.2 on 2026-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0003_alter_router_ip_alter_router_ip_vpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='Opcional si usas VPN', null=True, protocol='IPv4'),
        ),
    ]
